### ISSUE TITLE
Button on Video to manually watch or unwatch

### ISSUE THREAD

**Issue by chayes2** [sniklaus/youtube-watchmarker#105] opened 2023-05-30 01:21 UTC
I use the greyed screen with the 'Watched' flag settings. Sometimes I'd like to be able to manually toggle the watched / unwatched status on the screen. This would help differentiate partially-watched videos , or those you don't want to watch. Maybe a little button on the thumbnail.

Can this be done?

^-^

**Comment by sniklaus** [comment] 2023-10-09 20:21
Thanks for bringing this up! This seems to be a duplicate of #68, which is why I am closing this issue for now. Please don't hesitate to reopen it should I have been mistaken.

**Closed by sniklaus** 2023-10-09 20:21 UTC
