### ISSUE TITLE
Video's getting marked without even seeing them

### ISSUE THREAD

**Issue by Lucius6** [sniklaus/youtube-watchmarker#21] opened 2019-04-01 00:00 UTC
I have an issue that's going on for some weeks now. Videos are getting marked as watched without me even having watched them. Sometimes I refresh my subcriptions page and new videos are marked as watched. And no, I didn't watch on any other device. And yes my account is still secure, I even changed my passwords because that was my first tougth too that someone else was using my account for watching videos. I also tried to reinstall your add-on (even with a pc reboot in between).

**Comment by sniklaus** [comment] 2019-04-01 18:40
The addon occasionally gets a bad review due to someone else experiencing this issue and complaining about it. It is definitely a deal-breaker and I can totally understand your frustration.

Some basics, the addon gets notified when: 1) your tab navigates to a Youtube link, 2) the history state of your browser changes, for example by clicking on a link within the Youtube page, or 3) there is a web request to Youtube. My guess is that 3) is the culprit in your situation that causes the erroneous behavior. For example, there may be another addon that requests certain information about a YouTube video in the background which may let the Youtube Watchmarker believe that it is you navigating to that video. Do you by chance have any other extensions installed that interoperate with Youtube?

**Comment by Lucius6** [comment] 2019-04-01 20:23
I've disabled all 3 other add-ons (TamperMonkey, UBlock and VideoDownloadhelper), the last one I even deleted because I only used it once a long time ago, restarted FF and it still happened when I refreshed my subscription feed. I've taken some screens that I hope give some more clarity.

The first one I did because in my search history within your add-on you can see he loads multiple video's without anny title which I find odd because videos I actually watch get named there. Also you can see I havn't disabled the progress bar for watched video's which tie in with the second screen shot.
![YWM1](https://user-images.githubusercontent.com/49132759/55356691-9f58c500-54cb-11e9-88ac-09b8c44dcdf7.jpg)

A screenshot from my subscription feed where you can see that video's that get marked as watched incorectly are also missing the progress bar underneath them whilst those I've really watched have the progress bar/
![YWM2](https://user-images.githubusercontent.com/49132759/55356693-9f58c500-54cb-11e9-962e-122f433e6d24.jpg)

I hope this sheds some more light on what could cause this as I also saw those bad reviews for this problem. I've been using your add-on for a couple of years now and this is the first time sth goes wrong.

**Comment by Lucius6** [comment] 2019-04-01 20:25
I've disabled all 3 other add-ons (TamperMonkey, UBlock and VideoDownloadhelper), the last one I even deleted because I only used it once a long time ago, restarted FF and it still happened when I refreshed my subscription feed. I've taken some screens that I hope give some more clarity.

The first one I did because in my search history within your add-on you can see he loads multiple video's without anny title which I find odd because videos I actually watch get named there. Also you can see I havn't disabled the progress bar for watched video's which tie in with the second screen shot.
![YWM1](https://user-images.githubusercontent.com/49132759/55356691-9f58c500-54cb-11e9-88ac-09b8c44dcdf7.jpg)

A screenshot from my subscription feed where you can see that video's that get marked as watched incorectly are also missing the progress bar underneath them whilst those I've really watched have the progress bar/
![YWM2](https://user-images.githubusercontent.com/49132759/55356693-9f58c500-54cb-11e9-962e-122f433e6d24.jpg)

I hope this sheds some more light on what could cause this as I also saw those bad reviews for this problem. I've been using your add-on for a couple of years now and this is the first time sth goes wrong.

**Comment by wooziwoozi** [comment] 2019-04-11 15:08
I love this addon, but this started to happen to me today... I looked at my "Today" Subscriptions... and I just woke up... and half are marked as watched...

**Comment by wooziwoozi** [comment] 2019-04-11 15:45
I just noticed the videos I haven't watched have blank names in the moz-extension://f6e6dfa7-145e-45f4-a12b-128c53192b0b/content/index.html thingy settings.

**Comment by Lucius6** [comment] 2019-04-11 18:35
> I just noticed the videos I haven't watched have blank names in the moz-extension://f6e6dfa7-145e-45f4-a12b-128c53192b0b/content/index.html thingy settings.

Just like my first screenshot then. Now if he only would come to this site maybey things can get cleared up.

**Comment by sniklaus** [comment] 2019-04-13 18:49
Thank you for further investigating this @Lucius6, I greatly appreciate it! It is by the way not that I am ignoring you, I hear you loud and clear and I understand that this is a bug that renders this extension useless for you. However, I am still clueless as to what is causing this behavior. But since @wooziwoozi confirmed that the videos show up with an empty title, a quick fix would be to add a few lines that prevent videos from being added to the database if their title is empty.

**Comment by Lucius6** [comment] 2019-04-13 19:03
Sorry, was a bit rude indeed. I know how hectic life can be. I'll be waiting till you can programm that into the extention to try it out.

**Comment by sniklaus** [comment] 2019-04-13 21:38
I released version `3.0.2` that is currently being reviewed to address this issue. I would recommend clearing your history in the extension after updating it, before synchronizing it again.

**Comment by Lucius6** [comment] 2019-04-14 01:02
I've updated the add on and cleared the history like you said and at first it once again marked new video's as marked. But then just now I've watched one and they're all unmarked again. Don't know if that's the way it's supposed to work now, if so, good job of fixing this :)

**Comment by sniklaus** [comment] 2019-04-14 02:14
So it works as expected now and videos you haven't watched are no longer marked as such?

**Comment by Lucius6** [comment] 2019-04-14 12:46
I had disabled your add-on till yesterday and now I also noticed sth else that might be part of what caused the problem in the first place. When youtube loads, it loads my subscription feed from a few weeks ago, from around the time the issue started for me. I have to click on subscriptions in the left side menu to get my current subscription feed, and then he marks video's as watched that I still have to watch. But watching one video fixes this now. Anyway, as long as the add-on was disabled, my subscription feed loaded as should be when starting Firefox. 
So in some way, the problem still exists but now it's easily fixed by watching a video.

**Comment by sniklaus** [comment] 2019-04-14 17:42
There are four ways that will trigger a video to be watched: 1) by having you navigate to it, 2) from your browsers history, 3) from the browsing history on Youtube, and 4) from video feeds when Youtube itself marks videos as watched.

The last one seems to be (have been) the culprit in this case, the new Youtube tends to reuse old DOM elements. As such, it might reuse a DOM element from a video that has been watched for a new video, in turn making the extension believe that you watched it. I have added some additional checks that should prevent this from happening.

I am a little bit surprised by the behavior that you are experiencing right now. I have not heard from anyone that the extension prevents videos from automatically starting yet. You could try to temporarily revert to the old Youtube design to see if that has any effect: https://www.reddit.com/r/youtube/comments/834a9k/

**Comment by Lucius6** [comment] 2019-04-14 20:09
I didn't notice it till right now. I thougth that the not autpmtic starting to play from video's was a new feature youtube was testing for some reason. Then I disabled your extension because of the problem for which I opend this topic and I just tougth youtube cancelled it again. This untill I reanabled the extension to test the update and video's didn't start automaticly again. Disabled the extension again and they just played automaticly again.

Switching to the old Youtube design doesn't change that. I used the script posted in the comments as I couldn't figure out how to do it in FF. But now I kinda want to get back to the new design and removing the script doesn't work, it stays the old design :(

**Comment by sniklaus** [comment] 2019-04-14 20:20
I don't know which script you ran, but have you tried disabling said script to recover the new Youtube style? You can also try visiting: http://youtube.com/new

**Comment by Lucius6** [comment] 2019-04-14 20:23
The one in the reddit post ypu linked to. In the comment someone posted a script to revert Youtube back to the old design. In the meantime I have found a solution myself, I wanted to edit my previous post to delete that part as it became irrelevant :)

**Comment by wooziwoozi** [comment] 2019-04-14 20:25
I am not sure what the other person is talking about, but from my end I haven't noticed this happening again since the first day the issue popped up for me. If it pops up again I will report back. Thank you so much for the great support for a great add-on! Keep on being swell!

Off topic though, I have a question. When I sync the add-on to my YouTube, it finds I have 8000 watched videos. So.... are you telling me that Youtube actually saves this data and just refuses to work correctly? I had always assumed they deleted the data to save space or something, and that's why an extension based on my browser history made sense..... but..... it seems like YouTube is just unnecessarily being broken?

**Comment by Lucius6** [comment] 2019-04-14 20:29
And to be honest, videos not starting automaticly is also not such a big deal. I only noticed it that your extension seems to do that too so I just wanted it to let you know.

**Comment by sniklaus** [comment] 2019-04-14 20:49
@wooziwoozi: Youtube stores it, yes. I guess they do not mark old videos as watched to reduce the load on their servers. With the amount of users that they are serving, a query of your entire browsing history every time you navigate to a new page might just not be feasible. As such, they are likely just incorporating your most recent history.

@Lucius6: I wonder what is going on with your setup since the number and kind of issues that you are experiencing are inexplicable to me. Should you ever reformat and reconfigure your machine, I would be curious to hear about your experience with this extension in a clean / known-good environment.

**Comment by wooziwoozi** [comment] 2019-04-14 21:00
Ah I see, that makes sense actually. It has always annoyed me though, and I thank you tremendously for fixing the issue for those of us who seek out a solution! 

Take care!

**Comment by Lucius6** [comment] 2019-04-14 21:05
Strange, must be indeed sth more specific with me then. But again, no big deal for me. My machine has been cleaned a few months ago and will be again in the near future so I'll keep you posted.

**Comment by sniklaus** [comment] 2019-04-14 21:06
I am closing this issue in the meantime. Feel free to reopen it in case anything comes up! 👍

**Comment by wooziwoozi** [comment] 2019-06-12 08:56
Hello.. This is happening again. I don't know what is causing it. But I clicked on YouTube today to look at recommendations and they are all marked as watched.

**Comment by sniklaus** [comment] 2019-06-14 21:08
This is a really odd bug, my apologies for the trouble. I am afraid that I am still clueless as to why this is happening. 🙁

**Comment by wooziwoozi** [comment] 2019-06-14 21:56
It's no problem! I just wanted to let you know it is still happening. I haven't had the issue again since those two times though, yet.

**Comment by sniklaus** [comment] 2019-06-14 22:21
I definitely appreciate the update, otherwise I would still be under the impression that the most recent version fixed the issue!

**Comment by sniklaus** [comment] 2020-03-30 18:08
I have finished rewriting the extension from scratch and while I still do not know what the problem of this issue is, I hope that the new rewrite is able to address it. Thanks again for bringing this up!

**Closed by sniklaus** 2020-03-30 18:08 UTC
