### ISSUE TITLE
youtube watchmarker isnt working when i put in a direct link in the browser

### ISSUE THREAD

**Issue by helpvlc** [sniklaus/youtube-watchmarker#57] opened 2021-02-28 21:18 UTC
Look i wrote a novel but i guess the simple fact is HELLO IM DAVID BY THE WAY :-)

Your addon isnt working when i place a youtbe link directly in the address bar OR using the Youtube Subscription checker
The checker like placing a link in a tab and pressing enter on it your watchmarker still marks down you went to that location but NOTHING ON THE RIGHT IS BLOCKED AT ALL

Thats the simple problem of the the more complex one is i have abillion addons on the webbrowser firefox latest of course let me grab that info 86.0 (64-bit)
and windows 10 pro something under what the new one is i hear control panel is going away NOOOOOO.

Sorry um yeah type in a link press enter your addon puts the history of the youtube video in its database but the sides arent greyed out but search for that exact video in the search click on it and its like your addon wakes up and goes oh yeah this is a youtube video and blocks the watched videos with a grey overlay and a watched text

I hope you know what i am talking about it would be nice to see youtube checker work again along with your addon its so annoying seeing videos i have literally watched and accidentally clicking on them even though i should have watched them youtube checker makes sure of that but sometimes its annoying to see a NEW video but you watched it.

If you can check in to why this action is occuring it would be a good thing to know i can let you know the security options i have etc if you like but i think its something to do with your addon recognizing that the website directly going to a youtube video isnt recognizing that page as a page to activate on

Sorry to go on Just let me know what the go is i appreciate your time 
David
oh and thank you for a robust solution that has lasted as long as it has :-)

**Comment by sniklaus** [comment] 2021-05-09 17:45
I just tried to reproduce this but unfortunately fail to do so. As shown in the video below, it works just fine for me. Could it be that you have another extension enabled that interferes with the Youtube Watchmaker. Closing for now since I am unable to reproduce this, feel free to reopen if you have debugged this further and are certain that there isn't something else going on.


https://user-images.githubusercontent.com/1238034/117581821-a5123300-b0b3-11eb-922d-bad5f1c2f4fc.mp4

**Closed by sniklaus** 2021-05-09 17:45 UTC

**Comment by helpvlc** [comment] 2021-05-09 21:51
i litterally have made my own refresh for the page by making a
javascript bit for greasemonkey
it recognises your in a video page and from there it clicks on the
playlist and in half a second reclicks on the videos page and the
addon then recognises its on the videos page
I honestly dont know why its doing this could be one of a million
other addons but i guess i will put up with it till i can be bothered
doing some troubleshooting again

oh well whatever it probably is another addon
thank you anyway :-) Your addon is priceless in functionality i
appreciate it soooo much
