### ISSUE TITLE
Youtube Watch History only fetches specific number

### ISSUE THREAD

**Issue by TheTetrapod** [sniklaus/youtube-watchmarker#81] opened 2022-04-16 22:50 UTC
Hey! Love the add-on, thanks for fixing Google's mistakes. I'm currently using Watchmarker on Firefox in Windows, and whenever I try to fetch my gigantic watch history, it only retrieves 199 videos. I have tried it on both Firefox and Chrome, across 2 different PCs, so I'm wondering if this is a quirk of my Youtube account of a known issue. My database is up to 2500 thanks to my browser histories, but I would like to get a more complete list. I recommended the add-on to someone else, who uses Firefox on Linux, and it was able to pull over 10,000 videos, so I thought that was worth noting.

Thanks again!

**Comment by shoaibshakeel381** [comment] 2022-05-03 10:54
I think youtube by default only lists 200 items in a playlist or list request. Maybe we need to add support for pagination in fetch items request

**Comment by sniklaus** [comment] 2022-05-03 15:33
Duplicate of https://github.com/sniklaus/youtube-watchmarker/issues/74, hence closing this issue.

The extension supports pagination as shown below, it is unfortunately still unclear to me why it doesn't work for some users.

https://user-images.githubusercontent.com/1238034/166485456-7f37ac83-c90f-458b-b6ef-00af34f467ec.mp4

**Closed by sniklaus** 2022-05-03 15:33 UTC
