### ISSUE TITLE
Thumbnail watched state doesn't update on profile tabs

### ISSUE THREAD

**Issue by Terrance** [sniklaus/youtube-watchmarker#96] opened 2023-01-29 19:25 UTC
If you go to a channel's videos page (i.e. `https://www.youtube.com/<user>/videos`) and switch between the _Recently uploaded_ and _Popular_ tabs, the "Watched" thumbnail annotations stay in position, even if a watched video changes positions or is added to / removed from the page.

For example, if I've watched the fourth video shown on the _Recently uploaded_ tab, and then switch to _Popular_, the new fourth video on that page will be shown as watched even if not, and newly listed videos I have watched won't then be marked as watched.

Switching tabs doesn't change the URL, whereas the previous design of this page did, if that's relevant to when links get updated.

**Comment by sniklaus** [comment] 2023-01-30 07:00
Thanks for reporting this! Which version of the Watchmarker are you using? I am asking because it seems to work fine for me like shown in the attached video.

https://user-images.githubusercontent.com/1238034/215409018-633d854e-e463-4a38-a2be-b2554177b341.mp4

**Comment by Terrance** [comment] 2023-01-30 07:50
Ah sorry, this is 4.3.1 on Firefox, which appears to be current.

I've just had a closer look, and it appears to update correctly when I reach the bottom of the first page and the next one loads in.  Here's what I'm seeing:

https://user-images.githubusercontent.com/4025899/215418036-cd75afd1-b4dd-4c04-82c7-5b7e75a52dfa.mp4

The "watched" markers stay in place when switching tabs, but refresh to the correct videos after triggering infinite scrolling.

**Comment by lbmaian** [comment] 2023-04-20 11:28
This can happen if the total number of videos is small enough that scrolling down doesn't fetch more, since it won't trigger a refresh in watchmarker - refreshes only trigger when one of: URL changes, title changes, # thumbnails change, # thumbnails with progress bars change.

This is related to #56 and could be fixed if `yt-service-request-completed` event triggers a refresh at the next refresh interval.

**Comment by sniklaus** [comment] 2023-10-09 23:17
This seems to be a duplicate of #56 which is why I am closing this. Please reopen anytime should I be mistaken. :+1:

**Closed by sniklaus** 2023-10-09 23:17 UTC
