### ISSUE TITLE
Watched videos are no longer grayed out.

### ISSUE THREAD

**Issue by lordthuy941792** [sniklaus/youtube-watchmarker#80] opened 2022-04-07 16:11 UTC
Since the new Chrome update, watched videos only have small watched marker, no grayed out. The extension works fine on Firefox though.

**Comment by k5josh** [comment] 2022-04-08 06:09
I'm experiencing the same issue, though I don't even get the 'Watched' text marker. Tried enabling/disabling fading, greyscale, etc. to no effect.

**Comment by XP1** [comment] 2022-04-08 20:13
YouTube changed the HTML? The `img` is not in `yt-img-shadow`.

So after adding this CSS, it worked for me:
```
.youwatch-mark yt-image {
    opacity: 0.3;
    background-color: #FFFFFF;
    filter: grayscale(1.0);
}
```

**Comment by Kinomora** [comment] 2022-04-10 15:22
Also had this issue of the extension just mysteriously stop working when using chrome Version 99.0.4844.84.
Even more strangely, it seems to have started working again just today using chrome Version 100.0.4896.75.
Not sure if it was a browser update change that broke the plugin or if it was on youtube's end, but one thing I have noticed is that the videos watched in between when it stopped working and when it started working again are not marked as watched.

**Comment by finszterr** [comment] 2022-07-01 06:36
If I change channel or youtube account then greying out works.

**Comment by qounik** [comment] 2022-07-29 22:49
> If I change channel or youtube account then greying out works.

Yes, I found out the same. Is it because I have too many videos watched/liked?

**Comment by julianheuvel** [comment] 2022-10-10 21:14
So, I've been having the same issue for a few months now. Changing channel or YouTube account also doesn't seem to help. Anyone know of a fix?

**Comment by BlueBull010** [comment] 2022-11-04 19:49
> So, I've been having the same issue for a few months now. Changing channel or YouTube account also doesn't seem to help. Anyone know of a fix?
I have the same issue and can also fix it by switching to my second account. Something is amiss

**Comment by XP1** [comment] 2022-11-04 19:55
> > So, I've been having the same issue for a few months now. Changing channel or YouTube account also doesn't seem to help. Anyone know of a fix?
> 
> I have the same issue and can also fix it by switching to my second account. Something is amiss

[Did you try this CSS?](https://github.com/sniklaus/youtube-watchmarker/issues/80#issuecomment-1093314873)

**Comment by luke-bravenboer** [comment] 2022-11-04 20:11
Just started having this issue myself in Firefox within the past day or two - presumed related to the latest Youtube UI changes

**Comment by BlueBull010** [comment] 2022-11-04 20:50
> > > So, I've been having the same issue for a few months now. Changing channel or YouTube account also doesn't seem to help. Anyone know of a fix?
> > 
> > 
> > I have the same issue and can also fix it by switching to my second account. Something is amiss
> 
> [Did you try this CSS?](https://github.com/sniklaus/youtube-watchmarker/issues/80#issuecomment-1093314873)

I briefly looked at it but didn't have the time yet. I do now. Does it need to be placed in the youtube.css file in the extension subfolder found in the browser programdata folder?

**Comment by XP1** [comment] 2022-11-04 21:51
> I briefly looked at it but didn't have the time yet. I do now. Does it need to be placed in the youtube.css file in the extension subfolder found in the browser programdata folder? I'm on Chrome (well, Brave) by the way

You could try pasting [the above CSS](https://github.com/sniklaus/youtube-watchmarker/issues/80#issuecomment-1093314873) into a user CSS extension, such as [User CSS](https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb), or pasting this style rule below into [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) > Options > My filters:

```
youtube.com##.youwatch-mark yt-image:style(opacity: 0.3; background-color: #FFFFFF; filter: grayscale(1.0);)
```

**Comment by BlueBull010** [comment] 2022-11-05 00:07
> > I briefly looked at it but didn't have the time yet. I do now. Does it need to be placed in the youtube.css file in the extension subfolder found in the browser programdata folder? I'm on Chrome (well, Brave) by the way
> 
> You could try pasting [the above CSS](https://github.com/sniklaus/youtube-watchmarker/issues/80#issuecomment-1093314873) into a user CSS extension, such as [User CSS](https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb), or pasting this style rule below into [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) > Options > My filters:
> 
> ```
> youtube.com##.youwatch-mark yt-image:style(opacity: 0.3; background-color: #FFFFFF; filter: grayscale(1.0);)
> ```

Ah yes, that makes more sense than editing the extension CSS files. I have applied the uBock Origin method, since I already had that installed. I can confirm this resolves it, I now have proper function again on my main youtube account. Thank you for this workaround!

**Comment by sniklaus** [comment] 2022-11-09 18:19
Thanks everyone for chiming in! I just uploaded a new version which is already out for Firefox but still under review for Chrome (no idea how long this takes). Please let me know whether or not the version 4.2.2 fixes this issue, thanks!

**Comment by sniklaus** [comment] 2022-11-09 18:22
The listing for Chrome now shows 4.2.2 as well, let me know how it goes. :+1:

**Comment by BlueBull010** [comment] 2022-11-09 18:47
> The listing for Chrome now shows 4.2.2 as well, let me know how it goes. 👍

I have updated the extension to 4.2.2 and commented out the aforementioned uBlock Origin filter. So far it appears that the watch markers do indeed remain, even after closing and re-opening the browser. So, on first impression it seems that it is fixed. Should that change, I'll report back. Thank you for the effort of developing this mighty handy extension, thank you for fixing this issue and for still continuing to actively develop this extension so many years later!

**Comment by sniklaus** [comment] 2022-11-09 20:50
Thanks for confirming! I am hence closing this issue for now, please let me know (by replying here or by opening up a new issue) if this issue comes back or wasn't resolved after all. Thanks!

**Closed by sniklaus** 2022-11-09 20:50 UTC
