### ISSUE TITLE
I haven't watched that yet!

### ISSUE THREAD

**Issue by Seshua** [sniklaus/youtube-watchmarker#94] opened 2022-12-05 16:31 UTC
Hello Sniklaus

First off just wanted to say thankyou for such a great plugin, I remember when youtube did what this extension does. Don't know why they took it away or just didnt make it a hidden toggle in the settings for youtube.

Anyways, the issues is, it keeps marking videos as "Watched" even though I haven't watched them. Its that simple, nothing more to add.

not sure if you need this info but, I'm on firefox.

Have a great day!

**Comment by sniklaus** [comment] 2023-01-26 18:33
Thanks for reaching out! I am under the impression that this is a duplicate of #56 and am hence closing this one. Please feel free to reopen it in case I am mistaken. Thanks!

**Closed by sniklaus** 2023-01-26 18:33 UTC
