### ISSUE TITLE
Youtube sync issue

### ISSUE THREAD

**Issue by Almashina** [sniklaus/youtube-watchmarker#41] opened 2020-08-21 06:08 UTC
Hello!
Lately I've noticed that Youtube sync does only 199 imported videos. Checked on three different OS'es. Always strictly 199.
Before sync with Youtube did much more, about 20000 or like that, I think all YT history was imported everytime, and it was OK for me.
But now it can be problem a bit when using Youtube regularly on different rigs/os'es, for example I watch/listen 300 videos on rig №1, then i switch to rig №2 (another OS, FF and WatchMaker), rig №2 sync'ed Youtube with 199 new videos, difference is 101 videos that was watched but not in the WM base on rig №2.
I have three different OS'es using WM, dualboot at home and PC at work.
Any ideas about that, maybe it can be fixed?
Thank You.
_______________________
FF68.11.0esr on win10 and win7
WM ver.: 4.0.5
[screenshot](https://fastpic.ru/fullview/112/2020/0821/5d4ae97bccc6ece469ed133d6deddb5e.png.html)

**Comment by sniklaus** [comment] 2020-08-24 06:02
Fixed in the newest version, thanks for reporting! Please update if Firefox hasn't downloaded the newest version already and let me know whether or not the issue is resolved. Closing for now.

**Closed by sniklaus** 2020-08-24 06:02 UTC

**Comment by Almashina** [comment] 2020-08-24 09:34
Thank You, it seems that YT sync works now as usually, w/o 199 records restriction.
By the way, one more thing: YT sync in WM shows different numbers of records at different times.
It is not so important little bug / feature, but maybe not every time all entries of YT history  are fully loaded to WM database. 
Please check the screenshots taken in a row in one browser session step by step in several munutes:
[1st sync](https://fastpic.ru/view/112/2020/0824/b07fd45b90b70e03791536776d6c78ca.png.html) [2nd sync](https://fastpic.ru/view/112/2020/0824/350acebffc67cef5825105c565645c93.png.html) [3rd sync](https://fastpic.ru/view/112/2020/0824/6996e444977d79267c1b4b2666e348e6.png.html) [4th sync](https://fastpic.ru/view/112/2020/0824/07df071e7423b2ba7b67d64447d30ffe.png.html) 
After that 4 tries downloaded 19763 entries in a row (I didn't captured), then again:
[screenshot](https://fastpic.ru/fullview/112/2020/0824/a4706a1037f96b04ce970e0fbf2327a8.png.html)
¯\_(ツ)_/¯

**Comment by sniklaus** [comment] 2020-08-24 16:51
Thanks for letting me know and providing these details! I am afraid that there is little we can do about this. My best guess is that it depends on the specific Youtube endpoint that the extensions connects to during synchronization (we cannot influence this). I am also afraid that I do not know whether or not Youtube stores your entire history or just the recent activity. Like you, I can only synchronize about 20k through Youtube when my watch history is actually more than that.
