### ISSUE TITLE
"Synchronizing youtube" stopped working

### ISSUE THREAD

**Issue by Almashina** [sniklaus/youtube-watchmarker#48] opened 2020-11-28 15:32 UTC
"Synchronizing youtube" stopped working.
When doing manually sync, it only shows "Progress": ... Three dots forever and nothing else.
After having this issue on my ff78.5.0esr I checked it on fresh clean FF portable 78.5.0esr, all the same. YouTube itself works for me as usual.
ff78.5.0esr | wm4.0.8

**Comment by sniklaus** [comment] 2020-11-28 17:10
![out](https://user-images.githubusercontent.com/1238034/100521575-6d44ae00-3159-11eb-8320-5a40ca9b818b.gif)

Works for me, so I am afraid that I am unable to debug this. Does the browser console show any errors from the extension?

**Comment by Almashina** [comment] 2020-11-29 07:55
I've investigated this a bit. 
The problem exists on my main windows 7, but all works fine on my non-basic spare win10.
I tested different clean versions of portable mozilla's such as 64bit 78.5.0 - 78.4.1esr - 78.3.1esr - 83.0 english, all the same - sync not working.
This is console warning on WM tab on english ff83.0:
![0](https://user-images.githubusercontent.com/54445863/100536374-0c44d500-3242-11eb-9873-d6fe225c8217.png)

**Comment by Almashina** [comment] 2020-11-29 08:56
Dear sniklaus, I can check previous version of WM in my case if there is a repository somewhere by installing them manually.

**Comment by Almashina** [comment] 2020-11-29 12:33
I found that when enabling proxy by browsec addon - synchronization starts. When disabling - sync did not starts. Only browsers on win7 affected. FF/WM on win10 on the same rig with the same internet connection works fine. Firewall/antivirus software disabled for a while. I totally not understand this, it looks so strange.

**Comment by sniklaus** [comment] 2020-11-29 19:16
Thank you for debugging this in such great detail! My best guess is that using a proxy changes the HTTP header that are sent to Youtube which in turn affects Youtube's response. I am leaving this issue open for now to see whether others have similar issues, but I am afraid that I have no time/energy to fix a bug that only affects Windows 7 (which has a declining market share).

**Comment by Jw-Tan** [comment] 2020-12-02 05:05
Hi there, I have this issue as well, on Windows 10. I am however using Waterfox, but I've never had any issues with this addon before, and I do a watchmarker backup every month. On console, there are only warnings for CSS.
I tried Vivaldi and youtube syncs fine,

**Comment by Almashina** [comment] 2020-12-08 09:44
Hi all. For now Youtube sync function doesn't work on win10 and two win7's, second win7 is at work.
Two different ISP checked - fttb and mobile. 
Win10 has never had av/brandmauer/vpn software installed, almost fresh.
Clean fresh installed portable versions of mozilla's with no addons (besides WM) has been used.
Enabling proxy by browsec or hoxx addon or by connection my ff to a tor browser onion (socks 127.0.0.1 port 9150 with loaded tor) does not help anymore.
It just stunning on three dots.
Dear sniklaus, can You give me previous version of WM as a file for testing purposes?
![ezgif-4-fcc51e6327fd](https://user-images.githubusercontent.com/54445863/101467166-cc799e00-3963-11eb-8167-a15054fb9df0.gif)

**Comment by sniklaus** [comment] 2020-12-08 17:08
My apologies for the inconsistent behavior that you are experiencing. You can find previous versions of the extension through the version history on the Mozilla Addons page: https://addons.mozilla.org/en-US/firefox/addon/youtube-watchmarker/versions/

**Comment by Jw-Tan** [comment] 2020-12-09 13:42
Hi sniklaus, thanks for pointing out where to find the older versions. Moving back 1 version at a time, I had to revert back til 4.0.1 before Youtube sync could work. However, since my database is now reset, I tried to import my latest backup and I realised the import button does not do anything. No window pops up for me to select a file. Export works fine.

I then went back 1 more version to 3.0.2, and everything works (export, import, and both history & Youtube sync).

**Comment by Almashina** [comment] 2020-12-09 15:01
Hi dear **sniklaus**! Thanks for the link. 
I've tested few older versions and I can say that:
-- versions 4.0.2 and above (up to 4.0.8): sync get stuck at three dots;
-- versions 4.0.1 and below: sync allways get only 198 videos and stops happy "finished synchronizing youtube".
I really hope that this info will help resolve this issue. 
And I have no idea why I have this problem but you don't.
I checked Waterfox, all the same. I checked newly created YT profile, all the same. Vpn addon helped, but not for long.

**Comment by Jw-Tan** [comment] 2020-12-09 17:14
Oh I didn't even notice until you pointed it out Almashina. My youtube sync ends at 194 videos.

**Comment by Shajro** [comment] 2020-12-09 20:39
I have this issue too on Firefox 83 with Windows 10. Syncing works on 4.0.1, but checks only first 199 videos

**Comment by sniklaus** [comment] 2020-12-11 05:32
I just released version 4.0.9 which hopefully fixes this issue. Let me know how it goes, thanks!

**Comment by Almashina** [comment] 2020-12-11 06:22
Hooray! It works! =-) Thank You very match, dear **Simon**.
[hr]
**2all** If it doesn't work for you, please check the WM add-on version. It was updated first 4.0.1 -> 4.0.8, then it was updated to 4.0.9 on the second try.

**Comment by Jw-Tan** [comment] 2020-12-11 06:36
Hi, youtube sync works for me too. However, the import button doesn't work for me, as previously mentioned. I am on Waterfox Classic 2020.10. Does anyone have this issue, be it on the same browser or otherwise?

**Comment by Almashina** [comment] 2020-12-11 08:05
**Jw-Tan** Hi, import/export settings allways works fine in my case, I use it sometimes and checked it now, no problem on FF78.5.0esr .
I'll try Your browser plus WM at home and let You know in the late afternoon.

**Comment by Shajro** [comment] 2020-12-11 10:00
Thank you for update, it works now! However, it checks 405 last entries - it is fine for me, as sometimes I watch YT on phone, and do not need to synchronize whole history every time.
@Jw-Tan I can confirm that this issue occurs on Firefox 83, but i think that this topic should be opened as another ticket.

**Comment by Almashina** [comment] 2020-12-11 12:15
> Waterfox Classic 2020.10. Does anyone have this issue, be it on the same browser or otherwise?
I just checked fresh installed Waterfox Classic 2020.10 . Yes, there is the issue, pressing the "Import" button does nothing and pop-up window does not appear. Current G3.0.1 version work with WM addon fine, just like FF 78.x.x esr or FF 83. (It's all about the engine, I guess.)
> However, it checks 405 last entries
Maybe you should try one more time, because synchronization with YouTube often stops ahead of time, and next time sync can have 20ths records for example.

**Comment by sniklaus** [comment] 2020-12-12 05:10
I am happy to hear the synchronization works again!

Regarding the import in Waterfox Classic, could anyone of you check the browser console for any error messages when trying to import? I am happy to look into this further but I need some more information to be able to debug this.

**Comment by Jw-Tan** [comment] 2020-12-12 10:03
Not sure if this has what you need, but here's what appears on my console when I load the WM page.
[console log.txt](https://github.com/sniklaus/youtube-watchmarker/files/5682842/console.log.txt)

**Comment by Almashina** [comment] 2020-12-12 19:28
I tried check the browser console (Waterfox Classic 2020.12) on WM page, but it was always clean for me.

**Comment by sniklaus** [comment] 2020-12-12 19:45
I downloaded Waterfox Classic and found a workaround. When looking at the settings for the Youtube Watchmarker, open a console and execute `jQuery('#idDatabase_Import').find('input').click()` as shown in the video below. The first time you execute this command you may need confirm that the page is allowed to open popups and then run the command again. Closing this issue for now, everything seems to have been addressed. :+1: 

![output](https://user-images.githubusercontent.com/1238034/101993430-86784f00-3c6f-11eb-9851-eff3234b5eec.gif)

**Closed by sniklaus** 2020-12-12 19:45 UTC
