### ISSUE TITLE
Loss of progress preview when marked as watched.

### ISSUE THREAD

**Issue by ProfFancyPants** [sniklaus/youtube-watchmarker#43] opened 2020-09-15 17:15 UTC
I noticed this about a month ago.  When a video was marked as watched you could still see how much progress youtube thought you made in the video. Now, that no longer shows up unless I disable the add-on.  Thanks for all your hard work.

With watchmaker on:
![image](https://user-images.githubusercontent.com/7212413/93242650-2435ae00-f755-11ea-94bd-f36051294576.png)

With it disabled:
![image](https://user-images.githubusercontent.com/7212413/93242788-53e4b600-f755-11ea-8505-c840d34afc1e.png)

This happens in all window contexts, I am just showing watched because it is easiest to get a sample.

**Comment by sniklaus** [comment] 2020-09-15 17:18
Just to clarify, you want the "WATCHED" badge to show and the thumbnail to be grayed out but you still want the red progress bar?

**Comment by Astundi** [comment] 2020-09-18 01:38
I am missing this progress bar too! So much, it was the most important thing (and my only reason to use this add on) because it also showed me if I just opened the video or actually watched it. Because once opened it will be marked as watched.
I found the "Hide the progressbar that is being shown underneath watched videos." in the settings and took out the checkmark in hope it would show up again. But it doesn't.
I would aprreciate it very much if it's possible to ad that back in.
And yes, because YT forced the new layout on everyone, I also have the new layout now.

**Comment by sniklaus** [comment] 2020-10-04 02:54
Do you have any other extensions installed by chance that might interfere with the Youtube Watchmarker? It very much seems to be the case since the progress bars should be red and not blue. In any way, you can see in the video below that the progress bars show up for me if I uncheck the option to hide them in the settings. I am hence closing this issue for now since I cannot reproduce it. Feel free to provide additional feedback such that I can look into this further. 👍

![output](https://user-images.githubusercontent.com/1238034/95005826-b4774e00-05b1-11eb-8a22-cf84d6a60d6e.gif)

**Closed by sniklaus** 2020-10-04 02:54 UTC
